# =============================================================================
# Default Configuration
# =============================================================================

# Server Configuration
# host: Use "127.0.0.1" for local ComfyUI server
#       Use server's address/IP for remote server (e.g., "remote-server.example.com" or "192.168.1.100")
server:
  host: "127.0.0.1"  # Can be overridden by APP_SERVER_HOST env var
  port: 8188         # ComfyUI port (can be overridden by APP_SERVER_PORT env var)
  debug: false

# Media Configuration
media:
  base_dir: "media"  # Base directory for all media files
  paths:
    images: "images"  # Relative to base_dir
    videos: "videos"  # Relative to base_dir
    audio: "audio"    # Relative to base_dir
    other: "other"    # Relative to base_dir

# Image Generation
image:
  output_dir: "generated_images"
  default_seeds: 1
  seed_start: 1
  seed_end: 10
  video_duration: 3
  cfg: 1
  steps: 20

# Model Configuration
model:
  torch_device: "cuda"
  torch_dtype: "float16"
  torch_compile: false
  torch_blas_prefer_hipblaslt: 0
  hsa_override_gfx_version: "11.0.0"

# Paths Configuration
paths:
  prompt_media: "prompts.yaml"
  windows_output: "D:/Downloads/stable-diffusion-outputs"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"

# API Configuration
api:
  timeout: 30
  retries: 3
  backoff_factor: 0.5

# Security Configuration
security:
  api_key_header: "X-API-Key"
  jwt_secret: null  # Set this in environment-specific config
  jwt_algorithm: "HS256"
  jwt_expiry: 3600  # 1 hour

# Cache Configuration
cache:
  enabled: true
  ttl: 3600  # 1 hour
  max_size: 1000  # Maximum number of items to cache
